"""
Database migrations for the Azure Firewall Management application.

This package contains versioned migration scripts generated by Alembic.
Each migration script represents a change to the database schema.

Migration workflow:
1. Modify models in app/models/
2. Generate migration: alembic revision --autogenerate -m "description"
3. Review the generated migration in this directory
4. Apply migration: alembic upgrade head
"""